name: learn-github-actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 2"
